json.extract! rushing_statistic,
  :id,
  :player_name,
  :team,
  :position,
  :attempts_per_game,
  :attempts,
  :total_yards,
  :average_yards_per_attempt,
  :yards_per_game,
  :total_touchdowns,
  :longest_rush,
  :touchdown_in_longest_rush,
  :first_downs,
  :first_down_percentage,
  :twenty_plus_yards_each,
  :forty_plus_yards_each,
  :fumbles